CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(500),
    date_of_birth DATE,
    password VARCHAR(500)

    CONSTRAINT chk_password_length CHECK (PASSWORD IS NULL OR LENGTH(PASSWORD) >= 8)
);

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    balance DECIMAL(19, 2) DEFAULT 0.00,
    auto_increase_limit DECIMAL(19, 2) DEFAULT 0.00,

    CONSTRAINT fk_account_user
        FOREIGN KEY (user_id)
        REFERENCES "users"(id)
        ON DELETE CASCADE
);

CREATE TABLE email_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    email VARCHAR(200) NOT NULL,

    CONSTRAINT fk_email_user
        FOREIGN KEY (user_id)
        REFERENCES "users"(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE phone_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    phone VARCHAR(13) NOT NULL,

    CONSTRAINT fk_phone_user
        FOREIGN KEY (user_id)
        REFERENCES "users"(ID)
        ON DELETE CASCADE,

    CONSTRAINT uq_phone UNIQUE (phone)
);

CREATE INDEX idx_account_user_id ON ACCOUNT(user_id);
CREATE INDEX idx_email_user_id ON EMAIL_DATA(user_id);
CREATE INDEX idx_phone_user_id ON PHONE_DATA(user_id);
